[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]
CONSOLE=Console/dsp
IAXINFO=guest
TRUNK=DAHDI/g1
TRUNKMSD=1

[ligar]
exten => 0800,1,Answer()
exten => 0800,2,Dial(SIP/pedro)
exten => 0800,3,Hangup()

exten => 0900,1,Answer()
exten => 0900,2,Dial(SIP/maria)
exten => 0900,3,Hangup()